module.exports.userController = require("./user.controller")
module.exports.authController = require("./auth.controller")
module.exports.categoryController = require("./category.controller")
module.exports.restaurantController = require("./restaurant.controller")
module.exports.productController = require("./product.controller")
module.exports.orderController = require("./order.controller")